src/main/java/com/ermolaev/db/model/Message.java
package com.ermolaev.db.model;

import java.util.List;

import com.ermolaev.common.ComString;

public class Message {

	private Integer id;
	private String message;
	private String typeName;
	private Integer typeId;
	private Boolean ispattern;
	private Boolean available;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getTypeName() {
		return typeName;
	}
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
	public Integer getTypeId() {
		return typeId;
	}
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}
	public Boolean getIspattern() {
		return ispattern;
	}
	public void setIspattern(Boolean ispattern) {
		this.ispattern = ispattern;
	}
	public Boolean getAvailable() {
		return available;
	}
	public void setAvailable(Boolean available) {
		this.available = available;
	}
	public String getShortMessage()
	{
		if(this.message.length() > 100)
			return ComString.clearHTML(this.message.substring(0, 100) + "...");
		else
			return ComString.clearHTML(this.message);
	}
}

src/main/java/com/ermolaev/db/model/MessageType.java
package com.ermolaev.db.model;

public class MessageType {
	Integer id;
	String name;
	String description;
	Boolean available;
	Boolean deleted;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Boolean getAvailable() {
		return available;
	}
	public void setAvailable(Boolean available) {
		this.available = available;
	}
	public Boolean getDeleted() {
		return deleted;
	}
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}
}

src/main/java/com/ermolaev/db/model/Order.java
package com.ermolaev.db.model;

import java.sql.Date;
import java.sql.Time;

import com.ermolaev.common.ComString;
import com.ermolaev.common.MyCalendar;

public class Order {
	
	public static final int STATUS_WAITING = 1;
	public static final int STATUS_PROCESSING = 2;
	public static final int STATUS_SHIPPING = 3;
	public static final int STATUS_SHIPPED = 4; 
	public static final int STATUS_VIOLATION = 5;
	public static final int STATUS_UNPAID = 6;
	public static final int STATUS_FAIL = 7; 
	
	
	private Integer id;
	private Integer customerId;
	
	//message
	private String recipient;
	private String sender;
	private String message;
	private String comment;
	private Integer postcardId;
	
	//delivery time
	private Date deliveryDate;
	private Time startTime;
	private Time finishTime;
	
	private Integer complexity;
	private Float price;
	
	//address
	private String city;
	private String streetname;
	private String number;
	private String room;
	private String postalcode;
	
	private Integer status;
	private java.sql.Date tdate;
	private java.sql.Time ttime;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getCustomerId() {
		return customerId;
	}
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}
	public String getRecipient() {
		return recipient;
	}
	public void setRecipient(String recipient) {
		this.recipient = recipient;
	}
	public String getSender() {
		return sender;
	}
	public void setSender(String sender) {
		this.sender = sender;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public Date getDeliveryDate() {
		return deliveryDate;
	}
	public String getDeliveryDateS() {
		return deliveryDate.toString();
	}
	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}
	public Time getStartTime() {
		return startTime;
	}
	public String getStartTimeS() {
		return startTime.toString();
	}
	public void setStartTime(Time startTime) {
		this.startTime = startTime;
	}
	public Time getFinishTime() {
		return finishTime;
	}
	public String getFinishTimeS() {
		return finishTime.toString();
	}
	public void setFinishTime(Time finishTime) {
		this.finishTime = finishTime;
	}
	public Integer getComplexity() {
		return complexity;
	}
	public void setComplexity(Integer complexity) {
		this.complexity = complexity;
	}
	public Float getPrice() {
		return price;
	}
	public void setPrice(Float price) {
		this.price = price;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getStreetname() {
		return streetname;
	}
	public void setStreetname(String streetname) {
		this.streetname = streetname;
	}
	public String getNumber() {
		return number;
	}
	public void setNumber(String number) {
		this.number = number;
	}
	public String getRoom() {
		return room;
	}
	public void setRoom(String room) {
		this.room = room;
	}
	public String getPostalcode() {
		return postalcode;
	}
	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public java.sql.Date getTdate() {
		return tdate;
	}
	public void setTdate(java.sql.Date tdate) {
		this.tdate = tdate;
	}
	public java.sql.Time getTtime() {
		return ttime;
	}
	public void setTtime(java.sql.Time ttime) {
		this.ttime = ttime;
	}
	
	public Integer getPostcardId() {
		return postcardId;
	}
	public void setPostcardId(Integer postcardId) {
		this.postcardId = postcardId;
	}
	
	public String getFormatStatus()
	{
		switch(this.status)
		{
			case STATUS_WAITING : return "ui-status-waiting";
			case STATUS_PROCESSING : return "ui-status-processing";
			case STATUS_SHIPPING : return "ui-status-shipping";
			case STATUS_SHIPPED : return "ui-status-shipped";
			case STATUS_VIOLATION : return "ui-status-violation";
			case STATUS_UNPAID : return "ui-status-unpaid";
			case STATUS_FAIL : return "ui-status-fail";
			default: return "ERROR";
		}
	}
	
	public String getFormatStartTime()
	{
		MyCalendar cal = new MyCalendar();
		cal.setTimeInMillis(this.startTime.getTime());
		cal.setMinute(0);
		return cal.getSqlTime().toString();
	}
	
	public String getTextStatus()
	{
		switch(this.status)
		{
			case STATUS_WAITING : return "Ожидает";
			case STATUS_PROCESSING : return "Обрабатывается";
			case STATUS_SHIPPING : return "Доставляется";
			case STATUS_SHIPPED : return "Выполнено!";
			case STATUS_VIOLATION : return "Нарушение";
			case STATUS_UNPAID : return "Неоплачено";
			case STATUS_FAIL : return "Не выполнено";
			default: return "ERROR";
		}
	}	
	public Order copy()
	{
		Order or = new Order();
		or.id = this.id;
		or.customerId = this.customerId;
		or.recipient = this.recipient;
		or.sender = this.sender;
		or.message = this.message;
		or.comment = this.comment;
		or.deliveryDate = this.deliveryDate;
		or.startTime = this.startTime;
		or.finishTime = this.finishTime;
		or.complexity = this.complexity;
		or.price = this.price;
		or.city = this.city;
		or.streetname = this.streetname;
		or.number = this.number;
		or.room = this.room;
		or.postalcode = this.postalcode;
		or.status = this.status;
		or.tdate = this.tdate;
		or.ttime = this.ttime;
		
		return or;
	}
}

src/main/java/com/ermolaev/db/model/Postcard.java
package com.ermolaev.db.model;

public class Postcard {
	private Integer id;
	private String name;
	private String image;
	private Boolean available;
	private Boolean deleted;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getImage() {
		return image;
	}
	public void setImage(String image) {
		this.image = image;
	}
	public Boolean getDeleted() {
		return deleted;
	}
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}
	public Boolean getAvailable() {
		return available;
	}
	public void setAvailable(Boolean available) {
		this.available = available;
	}
}

src/main/java/com/ermolaev/db/model/PresentType.java
package com.ermolaev.db.model;

import java.io.Serializable;

import com.ermolaev.web.PresentTypeBean;

public class PresentType {
	
	private Integer id;
	private Integer order;
	private String name;
	private Boolean available;
	private Boolean deleted;
	
	public PresentType() {}
	
	public PresentType(String name, Boolean available, Boolean deleted)
	{
		this.name = name;
		this.available = available;
		this.deleted = deleted;
	}
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Boolean getAvailable() {
		return available;
	}
	public void setAvailable(Boolean available) {
		this.available = available;
	}
	public Boolean getDeleted() {
		return deleted;
	}
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Integer getOrder() {
		return order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}
}

src/main/java/com/ermolaev/web/DashboardBean.java
package com.ermolaev.web;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.apache.ibatis.session.SqlSession;

import com.ermolaev.db.mapper.OrderMapper;
import com.ermolaev.db.model.Order;
import com.ermolaev.web.db.Connection;

@ManagedBean(name="dashboard")
@ViewScoped
public class DashboardBean implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@ManagedProperty("#{conn}")
	private Connection conn;
	
	private List<Order> list;
	
	@PostConstruct
	public void init()
	{
		this.updateOrders();
	}
	
	public void updateOrders()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			OrderMapper mapper = session.getMapper(OrderMapper.class);
			this.list = mapper.getOrders(true, true);
		}
		finally
		{
			session.close();
		}
		this.showMsg("Статус заказа изменён!");
	}
	
	public void updateOrder(Order order)
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			OrderMapper mapper = session.getMapper(OrderMapper.class);
			mapper.changeStatus(order.getId(), order.getStatus());
			session.commit();
		}
		finally
		{
			session.close();
		}
	}
	public void showMsg(String msg)
	{
		FacesContext.getCurrentInstance()
		.addMessage("msg", 
				new FacesMessage(msg,  " ")
		);
	}
	
///////////////////////////////////////////////////////////////////////////////
	//	GETTER & SETTERS
///////////////////////////////////////////////////////////////////////////////
	
	public Connection getConn() {
		return conn;
	}

	public void setConn(Connection conn) {
		this.conn = conn;
	}

	public List<Order> getList() {
		return list;
	}

	public void setList(List<Order> list) {
		this.list = list;
	}
}

src/main/java/com/ermolaev/web/MessageBean.java
package com.ermolaev.web;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.apache.ibatis.session.SqlSession;

import com.ermolaev.db.mapper.MessageMapper;
import com.ermolaev.db.mapper.PresentMapper;
import com.ermolaev.db.model.Message;
import com.ermolaev.db.model.MessageType;
import com.ermolaev.db.model.Present;
import com.ermolaev.web.db.Connection;

@ManagedBean(name="message")
@ViewScoped
public class MessageBean implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@ManagedProperty("#{conn}")
	private Connection conn;
	
	private List<Message> list;
	private Integer id;
	private String message;
	private String typeName;
	private Integer typeId;
	private Boolean ispattern;
	private Boolean available;
	private List<MessageType> types;
	
	@PostConstruct
	public void init()
	{
		this.clearValues();
		this.updateList();
		this.updateTypesList();
	}
	
	public void updateList()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			MessageMapper mapper = session.getMapper(MessageMapper.class);
			list = mapper.getRealMessages();
		}
		finally
		{
			session.close();
		}
	}
	
	public void updateTypesList()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			MessageMapper mapper = session.getMapper(MessageMapper.class);
			types = mapper.getMessageTypes(true, false);
		}
		finally
		{
			session.close();
		}		
	}

	public void add()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			MessageMapper mapper = session.getMapper(MessageMapper.class);
			mapper.addMessage(message, typeId, ispattern, available);
			session.commit();
		}
		finally
		{
			session.close();
		}
		this.updateList();
		this.showMsg("Поздравление добавлено!");
	}
	
	public void update()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			MessageMapper mapper = session.getMapper(MessageMapper.class);
			mapper.updateMessage(id, message, typeId, ispattern, available);
			session.commit();
		}
		finally
		{
			session.close();
		}
		this.updateList();
		this.showMsg("Поздравление изменено!");
	}
	
	public void update(Message selectedElement)
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			MessageMapper mapper = session.getMapper(MessageMapper.class);
			mapper.updateMessage(
					selectedElement.getId(),
					selectedElement.getMessage(), 
					selectedElement.getTypeId(), 
					selectedElement.getIspattern(), 
					selectedElement.getAvailable()
			);
			session.commit();
		}
		finally
		{
			session.close();
		}
		this.updateList();
		this.showMsg("Поздравление изменено!");
	}
	
	public void delete(Message selectedElement)
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			MessageMapper mapper = session.getMapper(MessageMapper.class);
			mapper.deleteMessage(selectedElement.getId());
			session.commit(); //send date to DB
		}
		finally
		{
			session.close();
		}
		
		this.updateList();
		this.showMsg("Поздравление удалёно!");
	}
	
	public void setValues(Message value)
	{
		this.id = value.getId();
		this.message = value.getMessage();
		this.typeId= value.getTypeId();
		this.ispattern = value.getIspattern();
		this.available = value.getAvailable();
	}
	
	public void clearValues()
	{
		this.message = "";
		this.typeId = 1;
		this.ispattern = true;
		this.available = false;		
	}
	
	public Connection getConn() {
		return conn;
	}

	public void setConn(Connection conn) {
		this.conn = conn;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Integer getTypeId() {
		return typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public Boolean getIspattern() {
		return ispattern;
	}

	public void setIspattern(Boolean ispattern) {
		this.ispattern = ispattern;
	}

	public Boolean getAvailable() {
		return available;
	}

	public void setAvailable(Boolean available) {
		this.available = available;
	}
	
	public List<Message> getList() {
		return list;
	}

	public void setList(List<Message> list) {
		this.list = list;
	}

	public List<MessageType> getTypes() {
		return types;
	}

	public void setTypes(List<MessageType> types) {
		this.types = types;
	}

	public void showMsg(String msg)
	{
		FacesContext.getCurrentInstance()
		.addMessage("msg", 
				new FacesMessage(msg,  " ")
		);
	}
}

src/main/webapp/admin/Dashboard.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<ui:include src="/parts/header.xhtml" />
	<ui:include src="/parts/style_admin.xhtml" />
</h:head>
<h:body>

<center>

	<p:layout fullPage="true">
	
	    <p:layoutUnit position="center" style="padding:0px;" footer="Copyright © Happyship.ru 2015  Все права защищены"  resizable="true">
				
			<ui:include src="/admin/elements/menu.xhtml" />
			
			<h:form id="dataTableForm">
				<!-- СООБЩЕНИЕ -->
				<p:growl life="2500" for="msg" showDetail="false" id="msg"/>
			
			    <p:dataTable id="tbl" var="order" value="#{dashboard.list}"
                 paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                 paginator="true" rows="100" style="margin-bottom:20px">
 			 
			        <p:column width="60" style="text-align:center;">
			            <f:facet name="header">
			                <h:outputText value="Код" />
			            </f:facet>
			            #{order.id}
			        </p:column>
			        
			        <p:column width="200" style="text-align:center;">
			            <f:facet name="header">
			                <h:outputText value="Состояние" />
			            </f:facet>
			            <p:inplace  editor="true" saveLabel="Сохранить" cancelLabel="Отмена">
			            	<f:facet name="output">
	                			<div class="ui-status #{order.formatStatus}">#{order.textStatus}</div>
	            			</f:facet>
	            			<f:facet name="input">
	            				 <p:selectOneMenu  value="#{order.status}" style="width:125px">
						            <f:selectItem itemLabel="Ожидает" itemValue="1" />
						            <f:selectItem itemLabel="Обрабатывается" itemValue="2" />
						            <f:selectItem itemLabel="Доставляется" itemValue="3" />
						            <f:selectItem itemLabel="Выполнен!" itemValue="4" />
						            <f:selectItem itemLabel="Нарушение" itemValue="5" />
						            <f:selectItem itemLabel="Не выполнено" itemValue="7" />
						        </p:selectOneMenu>
								<p:ajax event="save" listener="#{dashboard.updateOrder(order)}" update=":dataTableForm:msg"/>
	            			</f:facet>
	            		</p:inplace>
			        </p:column>
			        
			        <p:column width="100" style="text-align:center;">
			            <f:facet name="header">
			                <h:outputText value="Дата" />
			            </f:facet>
			            #{order.deliveryDate}
			        </p:column>
			        
			        <p:column width="130" style="text-align:center;">
			            <f:facet name="header">
			                <h:outputText value="Время" />
			            </f:facet>
			            #{order.formatStartTime} + 2 часа
			        </p:column>
			        
			        <p:column width="100" style="text-align:center;">
			            <f:facet name="header">
			                <h:outputText value="Платёж" />
			            </f:facet>
			            #{order.price} руб.
			        </p:column>
			        
			        <p:column width="100" style="text-align:center;">
						<p:link outcome="/admin/Order.do" value="Обработать">
						    <f:param name="orderId" value="#{order.id}" />
						</p:link>
			        </p:column>
			        
			        <p:column>
			            <f:facet name="header">
			                <h:outputText value="Адрес"/>
			            </f:facet>
			            #{order.streetname}, д. #{order.number}, кв. #{order.room}
			        </p:column>
			        			        
			    </p:dataTable>
			</h:form>
	    </p:layoutUnit>
	    
	</p:layout>
</center>


</h:body>
</html>

src/main/webapp/admin/Order.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<ui:include src="/parts/header.xhtml" />
	<ui:include src="/parts/style_admin.xhtml" />
</h:head>
<h:body>
		<h:form id="form">	
		<h:panelGrid cellpadding="5" columns="3">
			<p:link outcome="/admin/Dashboard.do" value="Назад" />
			<p:commandButton 
				value="Печатать" 
				icon="fa fa-print" 
				onclick="window.print();"
				immediate="true"/>
			<p:commandButton
				id="processingButton"
				value="Обработать" 
				icon="fa fa-print" 
				actionListener="#{orderOne.makeProcessing}"
				disabled="#{orderOne.isProcessable}"
				update="processingButton"
				immediate="true"/>
		</h:panelGrid>
		
		<p:panelGrid columns="2" style="width:700px;">
			<h:outputText value="Данные заказа" style="font-weight:bold;"/>
			<h:outputText value="Открытка" style="font-weight:bold;"/>
			
			<p:panelGrid columns="2" columnClasses="ui-c1-order, ui-c2-order">				
		       	<h:outputText value="Код заказа" />
				<p:column style="text-align:center;">		
	              		<p:outputLabel value="#{orderOne.object.id}" />
		        </p:column>
		        			        
				<h:outputText value="Дата и время заказа" />
				<p:column style="text-align:center;">		
	              		#{orderOne.object.tdate} в #{orderOne.object.ttime}
		        </p:column> 	
		        
		        <h:outputText value="Состояние" />
				<p:column style="text-align:center;">		
	              		#{orderOne.object.textStatus}
		        </p:column> 
		        
		        <h:outputText value="Адрес" />
				<p:column style="text-align:center;">		
	              		 #{orderOne.object.streetname}, д. #{orderOne.object.number}, кв. #{orderOne.object.room}
		        </p:column> 	
		        
		        <h:outputText value="Дата доставки" />
				<p:column style="text-align:center;">		
	              		 #{orderOne.object.deliveryDate}
		        </p:column> 	
		        
		        <h:outputText value="Время доставки" />
				<p:column style="text-align:center;">		
	              		 #{orderOne.object.formatStartTime} + 2 часа
		        </p:column> 
		        
		        <h:outputText value="Сумма заказа" />
				<p:column style="text-align:center;">		
	              		 #{orderOne.object.price} руб.
		        </p:column> 						
			</p:panelGrid>
			
			<p:panelGrid columns="2" columnClasses="ui-c1-design-st, ui-c2-design-st, ui-c3-design-st">				
				<h:outputText value="Номер открытки" />
				<p:column style="text-align:center;">		
	              		#{orderOne.object.postcardId}
		        </p:column> 	
		        
		        <h:outputText value="Отправитель" />
				<p:column style="text-align:center;">		
	              		 #{orderOne.object.sender}
		        </p:column> 	
		        
		        <h:outputText value="Получатель" />
				<p:column style="text-align:center;">		
	              		 #{orderOne.object.recipient}
		        </p:column> 
		        
		        <h:outputText value="Сообщение" />
				<p:column style="text-align:center;">		
	              		 #{orderOne.object.message}
		        </p:column> 							
			</p:panelGrid>
			
		</p:panelGrid>
		
		<h:outputText value="Данные заказчика" style="font-weight:bold;"/>
		<p:panelGrid columns="3" style="width:700px;">
			<p:column style="text-align:center;">		
	             		 #{orderOne.customer.lastName}
	        </p:column>
	        
	        <p:column style="text-align:center;">		
	             		 #{orderOne.customer.firstName}
	        </p:column>
	        
	       	<p:column style="text-align:center;">		
	             		 #{orderOne.customer.middleName}
	        </p:column>
	        
	       	<p:column style="text-align:center;">		
	             		 #{orderOne.customer.phonenumber}
	        </p:column>
	        
	       	<p:column style="text-align:center;">		
	             		 #{orderOne.customer.email}
	        </p:column>
	        
	        <p:column style="text-align:center;">		
	             		 #{orderOne.customer.referral}
	        </p:column>
		</p:panelGrid>
		
		<h:outputText value="Список подарков" style="font-weight:bold;"/>
		<p:dataTable var="pres" value="#{orderOne.presents}" style="width:700px;">
		    <p:column headerText="Код" style="width:50px;">
		        <h:outputText value="#{pres.id}"/>
		    </p:column>
		 
		    <p:column headerText="Название">
		        <h:outputText value="#{pres.name}" />
		    </p:column>
		 
		    <p:column headerText="Цена" style="width:100px;">
		        <h:outputText value="#{pres.price}" />
		    </p:column>
		</p:dataTable>
		
	</h:form>


</h:body>
</html>