src/main/java/com/ermolaev/db/model/Customer.java
package com.ermolaev.db.model;

public class Customer {
	private Integer id;
	private String lastName;
	private String firstName;
	private String middleName;
	private String phonenumber;
	private String email;
	private String referral;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getMiddleName() {
		return middleName;
	}
	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}
	public String getPhonenumber() {
		return phonenumber;
	}
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getReferral() {
		return referral;
	}
	public void setReferral(String referral) {
		this.referral = referral;
	}
	
	public Customer copy()
	{
		Customer cs = new Customer();
		cs.lastName = lastName;
		cs.firstName = firstName;
		cs.middleName = middleName;
		cs.phonenumber = phonenumber;
		cs.email = email;
		cs.referral = referral;
		
		return cs;
	}
}

src/main/java/com/ermolaev/db/model/Setting.java
package com.ermolaev.db.model;

public class Setting {
	private String key;
	private String value;
	
	public String getKey() {
		return key;
	}
	public void setKey(String key) {
		this.key = key;
	}
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
}

src/main/java/com/ermolaev/web/model/SCUnit.java
package com.ermolaev.web.model;

import java.util.List;

public class SCUnit<ObjectType> {
	
	protected Integer id;
	protected String name;
	protected List<ObjectType> objects;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public List<ObjectType> getObjects() {
		return objects;
	}
	public void setObjects(List<ObjectType> objects) {
		this.objects = objects;
	}
	
	public void unselect() {}
	public void setSelected(Integer id) {}
	public ObjectType getSelected() { return null; }
}

src/main/java/com/ermolaev/web/CounterpartyBean.java
package com.ermolaev.web;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.apache.ibatis.session.SqlSession;

import com.ermolaev.db.mapper.CounterpartyMapper;
import com.ermolaev.db.mapper.PresentMapper;
import com.ermolaev.db.model.Counterparty;
import com.ermolaev.db.model.Present;
import com.ermolaev.web.db.Connection;

@ManagedBean(name="cparty")
@ViewScoped
public class CounterpartyBean implements Serializable {
	/**
	 * 
	 */
	public static final long serialVersionUID = 1L;
	
	@ManagedProperty("#{conn}")
	private Connection conn;
	
	private List<Counterparty> list;
	private List<Present> presentList;
	private Integer[] selectedList;
	private Integer id;
	private String name;
	private String phones;
	private String email;
	private String website;
	private String city;
	private String streetname;
	private String number;
	private String room;
	private String postalcode;
	
	@PostConstruct
	public void init()
	{
		this.clearValues();
		this.updateList();
		this.updatePresentList();
	}
	
	public void updateList()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			CounterpartyMapper mapper = session.getMapper(CounterpartyMapper.class);
			list = mapper.getCounterparties(false);
		}
		finally{
			session.close();
		}
	}
	
	public void updatePresentList(Counterparty selectedElement)
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			PresentMapper mapper = session.getMapper(PresentMapper.class);
			presentList = mapper.getPresentByCparty(selectedElement.getId(), false);
		}
		finally{
			session.close();
		}		
	}
	
	public void updatePresentList()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			PresentMapper mapper = session.getMapper(PresentMapper.class);
			presentList = mapper.getRealPresents();
		}
		finally{
			session.close();
		}	
	}
	
	public void add()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			CounterpartyMapper mapper = session.getMapper(CounterpartyMapper.class);
			mapper.addCounterparty(
					name, 
					phones,
					email, 
					website, 
					city, 
					streetname, 
					number, 
					room, 
					postalcode
			);
			session.commit();
			
			//get last cparty
			Counterparty last = mapper.getLastCounterparty(false);
			
			for(Integer it : selectedList)
			{
				mapper.addPresentToCparty(it, last.getId());
			}
			session.commit();
		}
		finally{
			session.close();
		}	
		
		this.updateList();
		this.clearValues();
		this.showMsg("Контрагент добавлен!");
	}
	
	public void update(Counterparty selectedElement)
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			CounterpartyMapper mapper = session.getMapper(CounterpartyMapper.class);
			mapper.updateCounterparty(
					selectedElement.getId(),
					selectedElement.getName(), 
					selectedElement.getPhones(),
					selectedElement.getEmail(), 
					selectedElement.getWebsite(), 
					selectedElement.getCity(), 
					selectedElement.getStreetname(), 
					selectedElement.getNumber(), 
					selectedElement.getRoom(), 
					selectedElement.getPostalcode()
			);
			session.commit();
		}
		finally{
			session.close();
		}		
		this.updateList();
		this.showMsg("Контрагент обновлён!");
	}
	
	public void update()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			CounterpartyMapper mapper = session.getMapper(CounterpartyMapper.class);
			mapper.updateCounterparty(
					this.id,
					this.name, 
					this.phones,
					this.email, 
					this.website, 
					this.city, 
					this.streetname, 
					this.number, 
					this.room, 
					this.postalcode
			);
			session.commit();
			
			//add presents to counterparty
			if(selectedList != null)
			{
				mapper.removeAllPresents(this.id);
				for(Integer it : selectedList)
				{
					mapper.addPresentToCparty(it, this.id);
				}
				session.commit();
			}
		}
		finally{
			session.close();
		}	
		this.updateList();
		this.showMsg("Контрагент обновлён!");
	}
	
	public void delete(Counterparty selectedElement)
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			CounterpartyMapper mapper = session.getMapper(CounterpartyMapper.class);
			mapper.deleteCounterparty(selectedElement.getId());
			session.commit();
		}
		finally{
			session.close();
		}	
		this.updateList();
		this.showMsg("Контрагент удалён");
	}
	
	public void setValues(Counterparty selectedElement)
	{
		this.id = selectedElement.getId();
		this.name = selectedElement.getName();
		this.phones = selectedElement.getPhones();
		this.email = selectedElement.getEmail();
		this.website = selectedElement.getWebsite();
		this.city = selectedElement.getCity();
		this.streetname = selectedElement.getStreetname();
		this.number = selectedElement.getNumber();
		this.room = selectedElement.getRoom();
		this.postalcode = selectedElement.getPostalcode();
		
		this.updatePresentList();
		this.updatePresentListById();
	}
	
	public void updatePresentListById()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			PresentMapper mapper = session.getMapper(PresentMapper.class);
			List<Present> presents = mapper.getAllPresentByCparty(this.id);
			selectedList = new Integer[presents.size()];
			for(int i = 0; i < presents.size(); i++)
				selectedList[i] = presents.get(i).getId();
		}
		finally
		{
			session.close();
		}
	}
	
	public void clearValues()
	{
		this.name = "";
		this.phones = "";
		this.email = "";
		this.website = "";
		this.city = "Ставрополь";
		this.streetname = "";
		this.number = "";
		this.room = "";
		this.postalcode = "";
		this.selectedList = null;
		this.updatePresentList();
	}

	public List<Counterparty> getList() {
		return list;
	}

	public void setList(List<Counterparty> list) {
		this.list = list;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhones() {
		return phones;
	}

	public void setPhones(String phones) {
		this.phones = phones;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStreetname() {
		return streetname;
	}

	public void setStreetname(String streetname) {
		this.streetname = streetname;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getRoom() {
		return room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public String getPostalcode() {
		return postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	public Connection getConn() {
		return conn;
	}

	public void setConn(Connection conn) {
		this.conn = conn;
	}
	
	public void showMsg(String msg)
	{
		FacesContext.getCurrentInstance()
		.addMessage("msg", 
				new FacesMessage(msg,  " ")
		);
	}

	public List<Present> getPresentList() {
		return presentList;
	}

	public void setPresentList(List<Present> presentList) {
		this.presentList = presentList;
	}

	public Integer[] getSelectedList() {
		return selectedList;
	}

	public void setSelectedList(Integer[] selectedList) {
		this.selectedList = selectedList;
	}
}

src/main/java/com/ermolaev/web/DashboardBean.java
package com.ermolaev.web;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.apache.ibatis.session.SqlSession;

import com.ermolaev.db.mapper.OrderMapper;
import com.ermolaev.db.model.Order;
import com.ermolaev.web.db.Connection;

@ManagedBean(name="dashboard")
@ViewScoped
public class DashboardBean implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@ManagedProperty("#{conn}")
	private Connection conn;
	
	private List<Order> list;
	
	@PostConstruct
	public void init()
	{
		this.updateOrders();
	}
	
	public void updateOrders()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			OrderMapper mapper = session.getMapper(OrderMapper.class);
			this.list = mapper.getOrders(true, true);
		}
		finally
		{
			session.close();
		}
		this.showMsg("Статус заказа изменён!");
	}
	
	public void updateOrder(Order order)
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			OrderMapper mapper = session.getMapper(OrderMapper.class);
			mapper.changeStatus(order.getId(), order.getStatus());
			session.commit();
		}
		finally
		{
			session.close();
		}
	}
	public void showMsg(String msg)
	{
		FacesContext.getCurrentInstance()
		.addMessage("msg", 
				new FacesMessage(msg,  " ")
		);
	}
	
///////////////////////////////////////////////////////////////////////////////
	//	GETTER & SETTERS
///////////////////////////////////////////////////////////////////////////////
	
	public Connection getConn() {
		return conn;
	}

	public void setConn(Connection conn) {
		this.conn = conn;
	}

	public List<Order> getList() {
		return list;
	}

	public void setList(List<Order> list) {
		this.list = list;
	}
}

src/main/java/com/ermolaev/web/DesignBean.java
package com.ermolaev.web;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

import org.apache.ibatis.session.SqlSession;

import com.ermolaev.db.mapper.SettingsMapper;
import com.ermolaev.web.db.Connection;

@ManagedBean(name="design")
@SessionScoped
public class DesignBean implements Serializable {
	/*
	 * 
	 */
	public static final long serialVersionUID = 1L;
	
	public static final String BG_IMAGE = "bg_img_url";
	public static final String BG_COLOR = "bg_color";
	public static final String BG_REPEAT = "bg_repeat";
	public static final String BG_POS_X = "bg_pos_x";
	public static final String BG_POS_Y = "bg_pos_y";
	public static final String BG_ATTACH = "bg_attach";
	public static final String LOGO_IMAGE = "logo_img_url";
	public static final String STEPONE_HEIGHT = "step_one_height";
	public static final String STEPTWO_HEIGHT = "step_two_height";
	
	private String bgImage = "/images/backg.jpg";
	private String logoImage = "/images/logo.png";
	private String bgColor = "0101DF";
	private String bgRepeat = "no-repeat";
	private String bgAttach = "fixed";
	private Integer bgPosX = 0;
	private Integer bgPosY = 0;
	private Integer stepOneHeight = 2800;
	private Integer stepTwoHeight = 2100;
	
	@ManagedProperty("#{conn}")
	private Connection conn;
	
	@PostConstruct
	public void init()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			SettingsMapper mapper = session.getMapper(SettingsMapper.class);
			Integer count = mapper.getCountParameter(BG_IMAGE);
			if(count == 0)
			{
				mapper.addParameter(BG_IMAGE, bgImage);
				mapper.addParameter(BG_COLOR, bgColor);
				mapper.addParameter(BG_REPEAT, bgRepeat);
				mapper.addParameter(BG_POS_X, bgPosX.toString());
				mapper.addParameter(BG_POS_Y, bgPosY.toString());
				mapper.addParameter(BG_ATTACH, bgAttach);
				mapper.addParameter(LOGO_IMAGE, logoImage);
				mapper.addParameter(STEPONE_HEIGHT, stepOneHeight.toString());
				mapper.addParameter(STEPTWO_HEIGHT, stepTwoHeight.toString());
				session.commit();
			}
			else
			{
				bgImage = mapper.getParameter(BG_IMAGE);
				bgColor = mapper.getParameter(BG_COLOR);
				bgRepeat = mapper.getParameter(BG_REPEAT);
				bgPosX = Integer.valueOf(mapper.getParameter(BG_POS_X));
				bgPosY = Integer.valueOf(mapper.getParameter(BG_POS_Y));
				bgAttach = mapper.getParameter(BG_ATTACH);
				logoImage = mapper.getParameter(LOGO_IMAGE);
				stepOneHeight = Integer.valueOf(mapper.getParameter(STEPONE_HEIGHT));
				stepTwoHeight = Integer.valueOf(mapper.getParameter(STEPTWO_HEIGHT));
			}
		}
		finally
		{
			session.close();
		}
	}
	
	public void updateAll()
	{
		SqlSession session = conn.getSessionFactory().openSession();
		try
		{
			SettingsMapper mapper = session.getMapper(SettingsMapper.class);
			mapper.setParameter(BG_IMAGE, bgImage);
			mapper.setParameter(BG_COLOR, bgColor);
			mapper.setParameter(BG_REPEAT, bgRepeat);
			mapper.setParameter(BG_POS_X, bgPosX.toString());
			mapper.setParameter(BG_POS_Y, bgPosY.toString());
			mapper.setParameter(BG_ATTACH, bgAttach);
			mapper.setParameter(LOGO_IMAGE, logoImage);
			mapper.setParameter(STEPONE_HEIGHT, stepOneHeight.toString());
			mapper.setParameter(STEPTWO_HEIGHT, stepTwoHeight.toString());
			session.commit();
		}
		finally
		{
			session.close();
		}		
	}

	public Connection getConn() {
		return conn;
	}

	public void setConn(Connection conn) {
		this.conn = conn;
	}

	public String getBgImage() {
		return bgImage;
	}

	public void setBgImage(String bgImage) {
		this.bgImage = bgImage;
	}

	public String getBgColor() {
		return bgColor;
	}

	public void setBgColor(String bgColor) {
		this.bgColor = bgColor;
	}

	public String getBgRepeat() {
		return bgRepeat;
	}

	public void setBgRepeat(String bgRepeat) {
		this.bgRepeat = bgRepeat;
	}

	public String getBgAttach() {
		return bgAttach;
	}

	public void setBgAttach(String bgAttach) {
		this.bgAttach = bgAttach;
	}

	public Integer getBgPosX() {
		return bgPosX;
	}

	public void setBgPosX(Integer bgPosX) {
		this.bgPosX = bgPosX;
	}

	public Integer getBgPosY() {
		return bgPosY;
	}

	public void setBgPosY(Integer bgPosY) {
		this.bgPosY = bgPosY;
	}

	public String getLogoImage() {
		return logoImage;
	}

	public void setLogoImage(String logoImage) {
		this.logoImage = logoImage;
	}

	public Integer getStepOneHeight() {
		return stepOneHeight;
	}

	public void setStepOneHeight(Integer stepOneHeight) {
		this.stepOneHeight = stepOneHeight;
	}

	public Integer getStepTwoHeight() {
		return stepTwoHeight;
	}

	public void setStepTwoHeight(Integer stepTwoHeight) {
		this.stepTwoHeight = stepTwoHeight;
	}
}

src/main/webapp/StepOne.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<ui:include src="/parts/header.xhtml" />
	<ui:include src="/parts/style.xhtml" />
	<title>Шаг 1 - Выбор подарков и открытки</title>
</h:head>
<h:body>

<center>
	<ui:include src="/parts/idle_update.xhtml" />
	
	<a href="Index.do">
		<img src="#{design.logoImage}" />
	</a>
	
	<br /><br />
	
	<p:layout style='width:90%;min-width:1000px;height: #{design.stepOneHeight}px;' >

	    <p:layoutUnit position="center" style="padding:20px;" footer="Copyright © Happyship.ru 2015  Все права защищены" resizable="true">

	    	<h:panelGrid style="width:100%;text-align:center;">
	    		<h:graphicImage url="images/topics/topic-present.png"/>
	    		<h:column>
	    			<h1>Выберите подарок</h1>
	    		</h:column>
	    	</h:panelGrid>

			<h:form>	
				<!-- КОМАНДА ДОБАВЛЕНИЯ ПОДАРКА -->
				<p:remoteCommand name="sendPresent" actionListener="#{order.addSelectedPresent}"/>
			</h:form>
			<h:form>
				<!-- КОМАНДА ОБНОВЛЕНИЯ ТЕКСТА ПОЗДРАВЛЕНИЯ -->
				<p:remoteCommand name="updateMessage" actionListener="#{order.updateMessage}"/>
			</h:form>
			<h:form>
				<!-- КОМАНДА ОБНОВЛЕНИЯ ОТКРЫТКИ -->
				<p:remoteCommand name="updatePostcard" actionListener="#{order.updatePostcard}"/>
			</h:form>
			
			<!-- ПАНЕЛЬ ВЫБОРА ПОДАРКОВ -->
	        <p:accordionPanel id="accPanel" value="#{scPresents.units}" var="presentList">
		        <p:tab title="#{presentList.name}">
		        	<p:dataGrid 
		        		var="pres" 
		        		value="#{presentList.objects}" 
		        		columns="4" 
		        		rows="1" 
		        		layout="grid" 
		        		paginator="true"
		        		paginatorTemplate="{PreviousPageLink} {NextPageLink}"
		        		id="dataList">
		        		
						<p:panel styleClass="#{pres.styleClassName}">
				            <h:panelGrid columns="1" style="width:100%;text-align:center;">
				   				<div style="width:100%;height:125px;text-align:center; display:table;">
				   					<div style="display: table-cell; vertical-align: middle;">
				   						<h2>#{pres.name}</h2>
				   					</div>
				   				</div>
				   				<h:graphicImage url="#{pres.imageurl}" width="190"/>
				   				<h2>#{pres.price} руб.</h2>
				   				<p:selectBooleanButton 
				   					value="#{pres.selected}"
				   					immediate="false"
				   					onchange="sendPresent([{name: 'present', value:'#{pres.id}'},{name: 'presentType', value:'#{pres.typeId}'}])"
				   					onLabel="Выбрано"
				   					offLabel="Не выбрано" 
				   					onIcon="fa fa-check" 
				   					offIcon="fa fa-unlink" 	   					
				   					styleClass="ui-select-button">
				   					<p:ajax event="change" update=":accPanel:dataList :messageForm:priceData" />
				   				</p:selectBooleanButton>
				            </h:panelGrid> 
				        </p:panel>		        	
		        	</p:dataGrid> 	 
		        </p:tab>
		    </p:accordionPanel>
		    
		    <h:panelGrid column="2" style="width:100%;text-align:center;">
	    		<h:graphicImage url="images/topics/topic-postcard.png"/>
	    		<h:column>
	    			<h1>Открытка</h1>
	    		</h:column>
	    	</h:panelGrid>
		    
	    	<p class="p-header">
				К вашему подарку может быть приложена открытка с вашим поздравлением!
				Заполните анкету ниже если хотите отправить открытку.
			</p>
			
			<!-- ПАНЕЛЬ ВЫБОРА СООБЩЕНИЯ -->
	        <p:accordionPanel value="#{scMessages.units}" var="messagesList">
		        <p:tab title="#{messagesList.name}">
		        	<p:dataGrid 
		        		var="mes" 
		        		value="#{messagesList.objects}" 
		        		columns="3" 
		        		rows="1" 
		        		layout="grid" 
		        		paginator="true"
		        		paginatorTemplate="{PreviousPageLink} {NextPageLink}"
		        		id="dataList">
		        		
			        <p:panel style="height:210px;">
				        <p class="p-messages" style="height:140px;">
				       		#{mes.message}
				        </p>
			        	<p:commandButton 
			        		value="Выбрать" 
			        		styleClass="ui-standart-cmd"
			        		icon="fa fa-pencil" 
			        		onclick="updateMessage([{name: 'messageId', value:'#{mes.id}'}])"
			        		update="messageForm:order-message"/>
			        </p:panel>	        	
		        	</p:dataGrid> 	 
		        </p:tab>
		    </p:accordionPanel>

			<h:form id="messageForm">
			<h:panelGrid columns="3" cellpadding="10" styleClass="msg-app ui-message-box" style="text-align:left;">
				<h:outputText value="Получатель:" styleClass="msg-topic-app" />
				<p:inputText value="#{order.recipient}" id="recipientId" style="font-size:20px;font-family: 'Open Sans', sans-serif;" maxlength="30" >
					<p:ajax event="change" process="@this" />
				</p:inputText>
				<h:outputText value="Используется в начале открытки. Например: Оля, Дима, Бурундучёк и т.д. Если не нужно не заполняйте." styleClass="msg-comment-app"/>
				
				<h:outputText value="Отправитель:" styleClass="msg-topic-app"/>
				<p:inputText value="#{order.sender}"  id="senderId" style="font-size:20px;font-family: 'Open Sans', sans-serif;" maxlength="30" >
					<p:ajax event="change" process="@this" />
				</p:inputText>
				<h:outputText value="Пишется внизу открытки. Если не нужно не заполняйте." styleClass="msg-comment-app"/>
			</h:panelGrid>
		
			<h:panelGrid columns="1" styleClass="msg-topic-free" >
				<h:outputText value="Далее введите текст сообщение если нужно:" styleClass="msg-topic-app" />
			</h:panelGrid>

			<h:panelGrid columns="2" cellpadding="5" styleClass="msg-app">
				<p:inputTextarea 
					value="#{order.message}"
					id="order-message"
					autoResize="false" 
					style="font-family: 'Open Sans', sans-serif;" 
					maxlength="400" 
					cols="55" 
					rows="8" />
				<h:graphicImage width="350" url="#{order.postcard.image}" id="order-postcard"/>
			</h:panelGrid>
			
			<p:dataGrid 
        		var="psc" 
        		value="#{order.postcardList}" 
        		columns="3" 
        		rows="1" 
        		layout="grid" 
        		paginator="true"
        		paginatorTemplate="{PreviousPageLink} {NextPageLink}"
        		id="dataList">	
       			<p:panel style="height:300px;">
       				<h:panelGrid columns="1" style="text-align:center;">
       					<p:commandButton 
       						style="width: 230px important;"
			        		value="Выбрать"
			        		styleClass="ui-standart-cmd"
			        		icon="fa fa-hand-o-left" 
			        		onclick="updatePostcard([{name: 'postcardId', value:'#{psc.id}'}])"
			        		update=":messageForm:order-postcard"/>		
	        			<div style="width:220px;height:220px;text-align:center;display:table;background: url('#{psc.image}'); background-position: 50% 50%;background-size: 220px 220px;">
		   					<div style="display: table-cell; vertical-align: middle;">
		   						<h3>#{psc.name}</h3>
		   					</div>
		   				</div>
		        	</h:panelGrid>
		        </p:panel>	   
        	</p:dataGrid>	
				    	
			<p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" style="font-size:20px;font-family: 'Open Sans', sans-serif;"/>
	    	<h1>Сумма заказа: <font color="1f6fe8"><h:outputText id="priceData" value="#{order.price}"/></font> рублей</h1>

	    	<p>
				Вы выбрали желемые подарки и сумма заказа вас устраивает? Тогда жмите далее и введите данные куда и когда нужно
				доставить подарок!
			</p>
	    	<div style="text-align:right;">
	    		<p:commandButton 
	    			value="Далее" 
	    			action="#{order.acceptStepOne}" 
	    			styleClass="ui-priority-primary ui-next-button" 
	    			immediate="true"/>
	    	</div>
	    	</h:form>
	    	<br />
	    </p:layoutUnit>
	    
	</p:layout>

</center>


</h:body>
</html>